"""Remote invocation entrypoint executed on the compute node.

A scheduler script generated by the SLURM/PBS/LSF backends launches this module
on the cluster::

    python -m foundry_studio.hpc.remote_invoke \\
        --model rfd3 --params params.json --out . --engine-mode auto

It is the cluster-side twin of :mod:`foundry_studio.hpc._local_runner`: it reads
the parameters + inputs, resolves the same engine code path (real foundry when
weights are present, otherwise the labelled simulation engine), writes outputs
into ``--out``, and emits a JSON result summary on stdout.  Shipping this single
module is all the cluster needs to run foundry-studio jobs — no GUI required.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from foundry_studio.db import StudioDB
from foundry_studio.engines.registry import resolve_engine


def run(model: str, params: dict, inputs_dir: Path, out_dir: Path, *, engine_mode: str, allow_simulation: bool) -> dict:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    # Synthesize a minimal job row the engine interface expects.
    inputs_dir = Path(inputs_dir)
    input_files = [
        {"role": "input", "filename": p.name, "name": p.stem}
        for p in sorted(inputs_dir.glob("*"))
        if p.is_file()
    ]
    job = {
        "id": "remote",
        "model": model,
        "name": f"remote-{model}",
        "status": "running",
        "params_json": json.dumps(params, ensure_ascii=False),
        "input_files_json": json.dumps(input_files, ensure_ascii=False),
        "engine_mode": engine_mode,
    }
    # The engine writes outputs into its own job dir; redirect it to out_dir.
    db = StudioDB(":memory:")
    workdir = out_dir.parent
    try:
        engine, effective_mode, _is_sim = resolve_engine(
            model,
            engine_mode=engine_mode,
            allow_simulation=allow_simulation,
            db=db,
            workdir=workdir,
            log_path=out_dir / "remote.log",
        )
        engine.workdir = out_dir  # force outputs here
        engine.initialize()
        result = engine.run(job)
        summary = {
            "ok": True,
            "model": model,
            "engine": effective_mode,
            "simulated": _is_sim,
            "outputs": [o.name for o in (result.outputs or [])],
        }
    except Exception as exc:  # noqa: BLE001
        summary = {"ok": False, "model": model, "error": f"{type(exc).__name__}: {exc}"}
    out_dir.joinpath("result.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="foundry-studio remote invoke")
    parser.add_argument("--model", required=True)
    parser.add_argument("--params", default="params.json", help="Path to a params JSON file")
    parser.add_argument("--inputs", default=".", help="Directory of input files")
    parser.add_argument("--out", default=".", help="Output directory")
    parser.add_argument("--engine-mode", default="auto")
    parser.add_argument("--allow-simulation", action="store_true", default=True)
    args = parser.parse_args(argv)
    try:
        params = json.loads(Path(args.params).read_text(encoding="utf-8"))
    except FileNotFoundError:
        params = {}
    except json.JSONDecodeError as exc:
        print(json.dumps({"ok": False, "error": f"bad params: {exc}"}))
        return 1
    summary = run(
        args.model,
        params,
        Path(args.inputs),
        Path(args.out),
        engine_mode=args.engine_mode,
        allow_simulation=args.allow_simulation,
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0 if summary.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
