"""Security utilities for sanitizing user-controlled inputs before shell / filesystem use."""

from __future__ import annotations

import re
import shlex
from pathlib import Path


class SecurityError(ValueError):
    """Raised when a sanitization check fails on a user-controlled value."""
    pass


# Job IDs are always lowercase hex strings generated by uuid.uuid4().hex
_JOB_ID_PATTERN = re.compile(r"^[a-f0-9]{1,32}$")


def sanitize_job_id(job_id: str | None) -> str:
    """Validate and return a job_id.

    Raises SecurityError if the value is not a valid lowercase hex string
    of at most 32 characters (matching ``uuid.uuid4().hex``).
    """
    if not job_id or not _JOB_ID_PATTERN.match(job_id):
        raise SecurityError(f"Invalid job_id: {job_id!r}")
    return job_id


def sanitize_path_component(name: str, *, allow_absolute: bool = False) -> str:
    """Prevent path-traversal attacks by validating a single path component.

    Args:
        name: The path component to validate.
        allow_absolute: Whether to permit absolute paths (e.g. ``/tmp/foo``).

    Raises SecurityError if the name contains ``..``, or is absolute when
    ``allow_absolute`` is False.
    """
    if ".." in name:
        raise SecurityError(f"Path traversal attempt: {name!r}")

    # Reject components that would escape the intended directory when joined.
    # A component is "safe" if Path(name).resolve() stays under the current
    # working directory *unless* allow_absolute is True.
    if not allow_absolute:
        resolved = Path(name).resolve()
        # The resolved path must not be absolute, or it must be under cwd.
        if resolved.is_absolute() and not str(resolved).startswith(str(Path.cwd())):
            # Note: we cannot use cwd as a reliable anchor when the process
            # may run in varied working directories.  Instead we forbid
            # absolute paths altogether when allow_absolute is False.
            raise SecurityError(f"Absolute path not allowed: {name!r}")

    return name


def sanitize_shell_arg(arg: str) -> str:
    """Return a shell-safe quoted version of *arg* using :func:`shlex.quote`.

    Use this whenever a user-controlled string is interpolated into a shell
    command string (``f"...{arg}..."`` or similar).  Prefer passing arguments
    as explicit list-argv to :mod:`subprocess` instead.
    """
    return shlex.quote(arg)


def build_sanitized_remote_path(base_workdir: str, job_id: str) -> str:
    """Build a remote working directory path from a base dir and a job_id.

    The ``base_workdir`` is the configured ``hpc_remote_workdir`` setting
    (a trusted string).  The ``job_id`` is validated as a proper UUID hex.

    Returns the joined path with ``job_id`` appended via ``/`` (Unix-style,
    compatible with all schedulers).
    """
    sanitized_job_id = sanitize_job_id(job_id)
    # base_workdir is trusted (from settings) but we strip trailing slashes.
    base = base_workdir.rstrip("/")
    return f"{base}/{sanitized_job_id}"
